service: hello-app-2
frameworkVersion: "3"
useDotenv: true
provider:
  name: aws
  deploymentMethod: direct
  runtime: python3.7

package:
  patterns:
    - "!*/**"
    - "../goodbye-app/**"
functions:
  hello:
    handler: "goodbye-app/handler.goodbye"
    environment:
      ENV_TEST: ${env:ENV_TEST}
    events:
      - httpApi:
          path: /
          method: get
