service: hello-app
frameworkVersion: "3"
useDotenv: true
provider: ${file(../provider.yml)}

functions:
  hello:
    handler: hello-app-2/handler.hello
    environment:
      ENV_TEST: ${env:ENV_TEST}
    events:
      - httpApi:
          path: /
          method: get
