service: hello-world
frameworkVersion: "3"

provider:
  name: aws
  #deploymentMethod: direct
  deploymentMethod: changesets
  runtime: python3.7

package:
  patterns:
    - "!*/**"
    - "app.py"

plugins:
  - serverless-offline
  - serverless-python-requirements
functions:
  hello:
    handler: app.lambda_handler
    events:
      - http:
          path: /hello
          method: GET
  goodbye:
    handler: app.lambda_handler
    events:
      - http:
          path: /goodbye
          method: GET
  api:
    handler: app.lambda_handler
    events:
      - http:
          path: /api/{proxy+}
          method: ANY
