service: hello-app
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  hello2:
    handler: handler.hello
    events:
      - http:
          path: /hello/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
              querystrings:
                foo: true
                bar: false
      - http:
          path: /api/{id}
          method: get
  hello3:
    handler: handler.hello
    events:
      - http:
          path: /hello/auth/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                foo: true
                bar: false
                baz: true
          authorizer:
            type: aws_iam
  hello4:
    handler: handler.hello
    events:
      - http:
          path: /hello/auth/2/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                foo: true
                bar: false
          authorizer:
            type: aws_iam
