service: hello-app
frameworkVersion: "3"

provider: ${file(../provider.yml)}

resources:
  Resources:
    s3:
      Type: AWS::S3::Bucket
  Outputs:
    s3bucket:
      Value: 
        Ref: s3
      Export:
        Name:
          Fn::Sub: ${AWS::StackName}-SecGroup

functions:
  HttpApiUrl:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  hello2:
    handler: handler.hello
    events:
      - http:
          path: /hello/{id}
          method: get
          request:
            parameters:
              paths:
                id: true
              querystrings:
                foo: true
                bar: false
      - http:
          path: /api/{id}
          method: get
  hello3:
    handler: handler.hello
    events:
      - http:
          path: /hello/auth/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                foo: true
                bar: false
                baz: true
          authorizer:
            type: aws_iam
  hello4:
    handler: handler.auth
    events:
      - http:
          path: /hello/auth/2/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                id: true
              querystrings:
                foo: true
                bar: false
          authorizer:
            type: aws_iam
